### PR TITLE
FIX: typo docker-compose commands

### PR DESCRIPTION
**Pull request by crydotsnake**

### CODE REVIEW

**Comment by macolo** [comment]
Hi @crydotsnake compose is now part of docker: https://docs.docker.com/engine/reference/commandline/compose_run/

**Comment by crydotsnake** [comment]
But i get the following output:

```bash
docker compose                                 
docker: 'compose' is not a docker command.
See 'docker --help'
```

**Comment by marksweb** [comment]
@crydotsnake whats your version?

```
% docker --version
Docker version 20.10.8, build 3967b7d
% docker compose

Usage:  docker compose [OPTIONS] COMMAND

Docker Compose

Options:
      --ansi string                Control when to print ANSI control characters ("never"|"always"|"auto") (default "auto")
      --env-file string            Specify an alternate environment file.
  -f, --file stringArray           Compose configuration files
      --profile stringArray        Specify a profile to enable
      --project-directory string   Specify an alternate working directory
                                   (default: the path of the Compose file)
  -p, --project-name string        Project name
```

**Comment by crydotsnake** [comment]
```
Docker version 20.10.8, build 3967b7d
docker-compose version 1.29.2, build 5becea4c
```

I should say that i'm using Debian.

**Comment by crydotsnake** [comment]
Fixed it.

https://docs.docker.com/compose/cli-command/

**Pull request closed without merging**
